"""
Structured output Pydantic v2 schemas used by AI nodes (LiteLLM / Ollama Cloud / LangGraph).
Ensures strict JSON Schema validation for all LLM node outputs.
"""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field
from app.domain.layout.schemas import LayoutAction
from app.domain.requirements.schemas import RequirementItem, SpatialPreference


class ParsedRequirementOutput(BaseModel):
    """Structured output emitted by RequirementParser LLM node."""
    model_config = ConfigDict(extra="forbid")

    summary: str = Field(..., description="Short summary of user requirements understood from input")
    items: List[RequirementItem] = Field(..., description="List of parsed requirement items")
    preferences: List[SpatialPreference] = Field(default_factory=list, description="Extracted preferences")
    target_density_seats: Optional[int] = Field(None, description="Explicitly mentioned target seat count")
    confidence_score: float = Field(default=0.9, ge=0.0, le=1.0, description="Overall parsing confidence")


class ClarificationQuestion(BaseModel):
    """A single clarification question generated when ambiguity is detected."""
    model_config = ConfigDict(extra="forbid")

    question_id: str = Field(..., description="Unique question ID")
    slot: str = Field(..., description="Target requirement slot in question (e.g. 'quantity_executive_desk')")
    question_text: str = Field(..., description="Clear user-facing question prompt")
    suggested_options: List[str] = Field(default_factory=list, description="Pre-baked answer choices")
    default_fallback_value: Optional[str] = Field(None, description="Fallback value if user skips")


class ClarificationRequest(BaseModel):
    """Structured output emitted by ClarificationManager node."""
    model_config = ConfigDict(extra="forbid")

    needs_clarification: bool = Field(..., description="True if mandatory questions must be answered")
    questions: List[ClarificationQuestion] = Field(default_factory=list, description="List of questions to ask")
    reasoning: str = Field(..., description="Explanation of why clarification is or is not needed")


class PlanningStrategy(BaseModel):
    """A semantic layout planning strategy proposed by PlanningStrategyGenerator node."""
    model_config = ConfigDict(extra="forbid")

    strategy_id: str = Field(..., description="Unique strategy ID")
    strategy_name: str = Field(..., description="Short title (e.g. 'Perimeter High Density Cluster')")
    description: str = Field(..., description="Detailed explanation of spatial approach")
    zoning_rules: List[str] = Field(..., description="Zoning instructions for optimizer")
    target_priorities: Dict[str, float] = Field(
        ..., description="Weighting factors for optimizer (e.g. {'circulation': 0.3, 'density': 0.5})"
    )


class PlanningStrategyList(BaseModel):
    """List of candidate strategies (3-5) generated by LLM for candidate layout creation."""
    model_config = ConfigDict(extra="forbid")

    strategies: List[PlanningStrategy] = Field(..., description="List of 3-5 candidate planning strategies")


class ChangeInterpreterOutput(BaseModel):
    """Structured output emitted by ChangeInterpreter node for iterative editing."""
    model_config = ConfigDict(extra="forbid")

    interpreted_intent: str = Field(..., description="Explanation of user's requested edit")
    actions: List[LayoutAction] = Field(..., description="Ordered list of actions to execute")
    confidence: float = Field(default=0.95, ge=0.0, le=1.0, description="Interpretation confidence")
